### ISSUE TITLE
Error: The CloudFormation template is invalid: null

### ISSUE THREAD

**Issue by ogis-onishi** [temyers/serverless-localstack#1]
Thanks you for providing great plugin! I am following the procedure on README.md but I got this error when I run 'serverless deploy'. Could you help me find what's wrong?

```
$ serverless deploy
Serverless: Packaging service...
Serverless: Using serverless-localstack plugin
Serverless: Using custom endpoint for CloudFormation: http://localstack:4581
Serverless: Using serverless-localstack plugin
Serverless: Using custom endpoint for CloudFormation: http://localstack:4581
Serverless: Uploading CloudFormation file to S3...
Serverless: Using serverless-localstack plugin
Serverless: Using custom endpoint for S3: http://localstack:4572
Serverless: Uploading artifacts...
Serverless: Uploading service .zip file to S3 (2.05 KB)...
Serverless: Using serverless-localstack plugin
Serverless: Using custom endpoint for S3: http://localstack:4572
Serverless: Validating template...
Serverless: Using serverless-localstack plugin
Serverless: Using custom endpoint for CloudFormation: http://localstack:4581
 
  Error --------------------------------------------------
 
  The CloudFormation template is invalid: null
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Stack Trace --------------------------------------------
 
Error: The CloudFormation template is invalid: null
    at provider.request.catch (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/validateTemplate.js:25:13)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:217:22)
    at PluginManager.spawn (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:229:17)
    at AwsDeploy.BbPromise.bind.then (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:88:48)
From previous event:
    at Object.deploy:deploy [as hook] (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:84:10)
    at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:217:55)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:217:22)
    at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:236:17)
    at variables.populateService.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:107:33)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:94:74)
    at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless:30:50)
    at <anonymous>
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           8.1.2
     Serverless Version:     1.16.1
 ```

**Comment by yohei1126** [comment]
This might be because URL of the cloudformation is ''https://s3.amazonaws.com/${bucketName}/${artifactDirectoryName}/${compiledTemplateFileName}".

https://github.com/serverless/serverless/blob/9e068b81b36b5009644f8fa94061d53da42757be/lib/plugins/aws/deploy/lib/validateTemplate.js#L11

**Comment by yohei1126** [comment]
The parameter is as follows: 

* service: CloudFormation
* method: validateTemplate
* param: {"TemplateURL":"https://s3.amazonaws.com/aws-nodejs-dev-ServerlessDeploymentBucket-724555A-Z14A-Z42/serverless/aws-nodejs/dev/1498832698130-2017-06-30T14:24:58.130Z/compiled-cloudformation-template.json"}

**Comment by yohei1126** [comment]
I tried with Node 4.4.7 and serverless 1.14.0 with the same configuration of https://travis-ci.org/temyers/serverless-localstack/jobs/236621765

I got the error.

```
# serverless deploy
Serverless: Packaging service...
Serverless: Using serverless-localstack plugin
Serverless: Using custom endpoint for CloudFormation: http://localstack:4581
Serverless: Using serverless-localstack plugin
Serverless: Using custom endpoint for CloudFormation: http://localstack:4581
Serverless: Uploading CloudFormation file to S3...
Serverless: Using serverless-localstack plugin
Serverless: Using custom endpoint for S3: http://localstack:4572
Serverless: Uploading artifacts...
Serverless: Uploading service .zip file to S3 (2.05 KB)...
Serverless: Using serverless-localstack plugin
Serverless: Using custom endpoint for S3: http://localstack:4572
Serverless: Updating Stack...
Serverless: Using serverless-localstack plugin
Serverless: Using custom endpoint for CloudFormation: http://localstack:4581
 
  Serverless Error ---------------------------------------
 
     socket hang up
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                 linux
     Node Version:       4.4.7
     Serverless Version: 1.14.0
```

**Comment by yohei1126** [comment]
The template was already uploaded.

```
$ curl http://localstack:4572/aws-nodejs-dev-ServerlessDeploymentBucket-724555A-Z14A-Z42/serverless/aws-nodejs/dev/1498835978135-2017-06-30T15:19:38.135Z/compiled-cloudformation-template.json
{"AWSTemplateFormatVersion":"2010-09-09",
"Description":"The AWS CloudFormation template for this Serverless application", 
...
```

CLI command is also failed.

```
$ aws --endpoint-url=http://localhost:4581 cloudformation validate-template --template-url http://localhost:4572/aws-nodejs-dev-ServerlessDeploymentBucket-724555A-Z14A-Z42/serverless/aws-nodejs/dev/1498835978135-2017-06-30T15:19:38.135Z/compiled-cloudformation-template.json

Unable to parse response (syntax error: line 1, column 54), invalid XML received:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
```

**Comment by temyers** [comment]
Hi Yohei,

Sorry, only just seen this issue.

This is still a WIP, but contributions welcome.  Would you be able to put together a test case to demonstrate the problem that we can add into the project?

I'll try investigate further...

**Comment by yohei1126** [comment]
I think we should fix build failures on Travis CI first. https://travis-ci.org/temyers/serverless-localstack/

**Comment by yohei1126** [comment]
I asked the atlassian guys about the following issues. https://bitbucket.org/atlassian/localstack/issues/42/unable-to-validate-cloudformation-template

```
CLI command is also failed.
$ aws --endpoint-url=http://localhost:4581 cloudformation validate-template --template-url http://localhost:4572/aws-nodejs-dev-ServerlessDeploymentBucket-724555A-Z14A-Z42/serverless/aws-nodejs/dev/1498835978135-2017-06-30T15:19:38.135Z/compiled-cloudformation-template.json

Unable to parse response (syntax error: line 1, column 54), invalid XML received:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
```

**Comment by justinm** [comment]
It doesn't appear Localstack supports the validateTemplate command. I'm working on a big PR that should address this in the meantime.

**Comment by temyers** [comment]
I got sidetracked after my initial push for this hence the current state it's in.

Agree that we need to get the integration tests working first.  I'll try and use this to contribute to validate template, if only a noddy implementation (i.e. validate the JSON/YAML and always pass).  @justinm have you already looked into contributing the same thing to localstack?

**Comment by temyers** [comment]
Ok, I'm going to close this one.
