### ISSUE TITLE
Service deployment fails

### ISSUE THREAD

**Issue by flosky** [temyers/serverless-localstack#13]
When calling `serverless deploy --stage dev`, I get following error:

```bash
Serverless: Using serverless-localstack-plugin
Serverless: Reconfiguring service apigateway to use http://localhost:4567
Serverless: Reconfiguring service cloudformation to use http://localhost:4581
Serverless: Reconfiguring service cloudwatch to use http://localhost:4582
Serverless: Reconfiguring service lambda to use http://localhost:4574
Serverless: Reconfiguring service dynamodb to use http://localhost:4567
Serverless: Reconfiguring service s3 to use http://localhost:4572
Serverless: Reconfiguring service ses to use http://localhost:4579
Serverless: Reconfiguring service sns to use http://localhost:4575
Serverless: Reconfiguring service sqs to use http://localhost:4576
Serverless: Reconfiguring service S3 to use http://localhost:4572
Serverless: Reconfiguring service CloudFormation to use http://localhost:4581
Serverless: Reconfiguring service SNS to use http://localhost:4575
Serverless: Reconfiguring service Lambda to use http://localhost:4574
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Uploading CloudFormation file to S3...
 
  Serverless Error ---------------------------------------
 
  The specified bucket does not exist
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           6.11.1
     Serverless Version:     1.19.0

```

and localstack returns the following:

```bash
ERROR:localstack.services.generic_proxy:Error forwarding request: An error occurred (ValidationError) when calling the DescribeStackResources operation: Stack with id my-test-service-dev does not exist Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/localstack/services/generic_proxy.py", line 189, in forward
    path=path, data=data, headers=forward_headers, response=response)
  File "/usr/local/lib/python3.5/site-packages/localstack/services/cloudformation/cloudformation_listener.py", line 184, in return_response
    template_deployer.deploy_template(template, req_data.get('StackName')[0])
  File "/usr/local/lib/python3.5/site-packages/localstack/utils/cloudformation/template_deployer.py", line 467, in deploy_template
    stack_resources = describe_stack_resources(stack_name, resource_id)
  File "/usr/local/lib/python3.5/site-packages/localstack/utils/cloudformation/template_deployer.py", line 205, in describe_stack_resources
    resources = client.describe_stack_resources(StackName=stack_name, LogicalResourceId=logical_resource_id)
  File "/usr/local/lib/python3.5/site-packages/botocore/client.py", line 253, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.5/site-packages/botocore/client.py", line 557, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ValidationError) when calling the DescribeStackResources operation: Stack with id my-test-service-dev does not exist
```

this is my `serverless.yml`:

```yaml
service: my-test-service

plugins:
  - serverless-plugin-localstack

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-central-1

custom:
  localstack:
    host: http://localhost
    debug: true
    endpoints:
      S3: http://localhost:4572
      CloudFormation: http://localhost:4581
      SNS: http://localhost:4575
      Lambda: http://localhost:4574

functions:
  hello:
    handler: src/hello/hello.handler
```

I think this is related to this: https://github.com/localstack/localstack/issues/101

But as far as I can see, localstack should support creating the resources via CloudFormation now.
Does anyone know what to do in order to get a simple deployment running?

**Comment by ssabnis** [comment]
I am getting the similar error when deployed localstack on docker.

```
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/endpoint.py", line 141, in make_request
return self._send_request(request_dict, operation_model)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/endpoint.py", line 170, in _send_request
success_response, exception):
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/endpoint.py", line 249, in _needs_retry
caught_exception=caught_exception, request_dict=request_dict)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/hooks.py", line 227, in emit
return self._emit(event_name, kwargs)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/hooks.py", line 210, in _emit
response = handler(**kwargs)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/retryhandler.py", line 183, in __call__
if self._checker(attempts, response, caught_exception):
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/retryhandler.py", line 251, in __call__
caught_exception)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/retryhandler.py", line 277, in _should_retry
return self._checker(attempt_number, response, caught_exception)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/retryhandler.py", line 317, in __call__
caught_exception)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/retryhandler.py", line 223, in __call__
attempt_number, caught_exception)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
raise caught_exception
EndpointConnectionError: Could not connect to the endpoint URL: "http://localhost.localdomain:4569/"

```

**Comment by kadrach** [comment]
Experiencing similar issues as @flosky with current localstack versions.

- Initial deploy fails with "empty" error message from serverless and DescribeStack errors as shown in above example
- Subsequent attempt at "serverless deploy" fails with missing bucket errors. Manually checking the localstack CF endpoint, I can see a "stack" has been created, but no buckets.

Running localstack from source via `make infra`, this gets a lot further:

```
Serverless: Using serverless-localstack-plugin       
Serverless: Reconfiguring service apigateway to use http://localhost:4567                                 
-snip-                                     
Serverless: Reconfiguring service sqs to use http://localhost:4576                                        
Serverless: Packaging service...                     
Serverless: Excluding development dependencies...    
Serverless: Creating Stack...                        
Serverless: Checking Stack create progress...        
..                        
Serverless: Stack create finished...                 
Serverless: Uploading CloudFormation file to S3...   
Serverless: Uploading artifacts...                   
Serverless: Uploading service .zip file to S3 (161.67 MB)...                                              
Serverless: Validating template...                   
Serverless: Skipping template validation: Unsupported in Localstack                                       
Serverless: Updating Stack...                        
                          
  Serverless Error ---------------------------------------                                                
                          
                          
  Get Support --------------------------------------------                                                
-snip-                          
  Your Environment Information -----------------------------                                              
     OS:                     linux                   
     Node Version:           8.2.0                   
     Serverless Version:     1.24.1                  
```

The following repeats four times in the localstack log:
```
2017-12-06T21:30:52:ERROR:localstack.services.generic_proxy: Error forwarding request: list index out of range Traceback (most recent call last):
  File "/localstack/localstack/services/generic_proxy.py", line 215, in forward
    updated_response = self.proxy.update_listener.return_response(**kwargs)                               
  File "/localstack/localstack/services/cloudformation/cloudformation_listener.py", line 183, in return_response
    template_deployer.deploy_template(template, req_data.get('StackName')[0])                             
  File "/localstack/localstack/utils/cloudformation/template_deployer.py", line 485, in deploy_template
    resource['__details__'] = stack_resources[0]     
IndexError: list index out of range                  
```
This appears to be an issue with localstack rather than this plugin.

**Comment by temyers** [comment]
I'm going to close this, as it's an upstream issue with localstack.

Integration testing of a simple deployment now works, although it can fail first time due to a timing issue and the S3 bucket not reporting as existing.

More complex deployment issues with localstack should be raised with the localstack project directly: https://github.com/localstack/localstack
