### ISSUE TITLE
my deployment seems to work but I get some kind of parse error...

### ISSUE THREAD

**Issue by st33v** [temyers/serverless-localstack#24]
Serverless: Invoke aws:deploy:deploy
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
..
Serverless: Stack create finished...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service .zip file to S3 (918 B)...
Serverless: Validating template...
Serverless: Skipping template validation: Unsupported in Localstack
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
..
Serverless: Stack update finished...
Serverless: Invoke aws:info

  Serverless Error ---------------------------------------

  Attribute without value
Line: 13
Column: 70
Char: a

  Stack Trace --------------------------------------------

ServerlessError: Attribute without value
Line: 13
Column: 70
Char: a
    at BbPromise.fromCallback.catch.err (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:258:33)
From previous event:
    at persistentRequest (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:247:13)
    at doCall (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:205:9)
    at BbPromise (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:216:14)
From previous event:
    at persistentRequest (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:203:38)
    at Object.request.requestQueue.add [as promiseGenerator] (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:237:49)
    at Queue._dequeue (/usr/local/lib/node_modules/serverless/node_modules/promise-queue/lib/index.js:153:30)
    at /usr/local/lib/node_modules/serverless/node_modules/promise-queue/lib/index.js:109:18
From previous event:
    at Queue.add (/usr/local/lib/node_modules/serverless/node_modules/promise-queue/lib/index.js:94:16)
    at AwsProvider.request (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:237:39)
    at LocalstackPlugin.interceptRequest (/usr/local/lib/node_modules/serverless-localstack/src/index.js:150:17)
    at AwsInfo.getStackInfo (/usr/local/lib/node_modules/serverless/lib/plugins/aws/info/getStackInfo.js:23:26)
From previous event:
    at Object.aws:info:gatherData [as hook] (/usr/local/lib/node_modules/serverless/lib/plugins/aws/info/index.js:56:10)
    at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:372:55)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:372:22)
    at PluginManager.spawn (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:390:17)
    at AwsInfo.BbPromise.bind.then (/usr/local/lib/node_modules/serverless/lib/plugins/aws/info/index.js:49:48)
From previous event:
    at Object.deploy:deploy [as hook] (/usr/local/lib/node_modules/serverless/lib/plugins/aws/info/index.js:45:10)
    at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:372:55)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:372:22)
    at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:403:17)
    at variables.populateService.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:102:33)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
    at process.topLevelDomainCallback (domain.js:101:23)
From previous event:
    at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:89:74)
    at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless:42:50)
    at <anonymous>

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           9.7.1
     Serverless Version:     1.26.1

**Comment by juancho088** [comment]
+1

**Comment by temyers** [comment]
I think this is a mismatch between the response returned from localstack and the expected response from serverless.

Can you create an [example](https://stackoverflow.com/help/mcve), as a failing test and submit as a PR?

**Comment by juancho088** [comment]
Ok, I found the error but not sure how to proceed with the fix. Basically the problem is that LocalStack is sending this xml as response:

```
<DescribeStacksResponse>
  <DescribeStacksResult>
    <Stacks>
      <member>
        <StackName>myproject-local</StackName>
        <StackId>arn:aws:cloudformation:us-east-1:123456789:stack/myproject-local/fd428008-b59a-4f3f-8c74-708decab87bc</StackId>
        <CreationTime>2010-07-27T22:28:28Z</CreationTime>
        <StackStatus>UPDATE_COMPLETE</StackStatus>
        <NotificationARNs/>
        <DisableRollback>false</DisableRollback>
        <Outputs>
          <member>
            <OutputKey>HelloLambdaFunctionQualifiedArn</OutputKey>
            <OutputValue><moto.awslambda.models.LambdaVersion object at 0x7f82f8363090></OutputValue>
          </member>
          <member>
            <OutputKey>ServerlessDeploymentBucketName</OutputKey>
            <OutputValue>myblockbuster-local-ServerlessDeploymentBucket-69429724417A-Z</OutputValue>
          </member>
          <member>
            <OutputKey>ServiceEndpoint</OutputKey>
            <OutputValue>https://<moto.apigateway.models.RestAPI object at 0x7f82f8363c10>.execute-api.us-east-1.amazonaws.com/local</OutputValue>
          </member>
        </Outputs>
        <Parameters>
        </Parameters>
        <Tags>
            <member>
              <Key>STAGE</Key>
              <Value>local</Value>
            </member>
        </Tags>
      </member>
    </Stacks>
  </DescribeStacksResult>
</DescribeStacksResponse>
```

As you can see in the `<OutputValue>` the value starts with `<` so for the sax parser it's like if it was starting a new tag instead of giving a value. So for instance in this specific case:

```
<OutputValue><moto.awslambda.models.LambdaVersion object at 0x7f82f8363090> </OutputValue>
```

It assumes that `moto.awslambda.modelsLambdaVersion` is a tag inside `OutputValue`.  So the error itself is something that moto models don't  have `toString` methods (and not sure if they should). The solution that I'm seeing right now is to intercept the response before the parsing, however what values should we use? or which function should we intercept to make a workaround of this stuff?

**Comment by tamanjoku** [comment]
Anybody found a resolution or a workaround to this issue?

**Comment by upmcsean** [comment]
I'm still seeing this issue.  Has this been fixed or is there a workaround?
