### ISSUE TITLE
Java8 Lambda deployment error

### ISSUE THREAD

**Issue by metapp** [temyers/serverless-localstack#26]
## Description

I'm trying to use this plugin in conjunction with [Localstack](https://github.com/localstack/localstack) and serverless which, to my knowledge, will simply point Serverless to the instances running on my local machine instead of aws. However I'm having an issue when deploying it using Serverless. 

It seems that it might have something to do with the aws credentials just by looking through the code; however I'm 100% clear on what I'm doing wrong/missing. 

**Config:**
```
plugins:
  - serverless-localstack
custom:
  localstack:
    debug: true
    stages: local
    endpointFile: /Users/yendor/localstack/config/endpoints.json
```

**Credentials: .aws/credentials**
```
aws_access_key_id=admin
aws_secret_access_key=admin
```
_**NOTE: localstack should ignore the value of the credentials as it deploys it locally. The file has to be in existence though. I've tried it both with real aws credentials and fake ones, both produce the same result.**_

**Stacetrace:**
```
yendor@Yendors-MBP~ $ serverless deploy --stage local --v
Serverless: Load command run
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command emit
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command deploy
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Invoke aws:common:validate
Serverless: Loading endpointJson from /Users/yendor/localstack/config/endpoints.json
Serverless: Intercepting service S3
Serverless: Intercepting service DynamoDB
Serverless: Intercepting service CloudFormation
Serverless: Intercepting service Elasticsearch
Serverless: Intercepting service ES
Serverless: Intercepting service SNS
Serverless: Intercepting service SQS
Serverless: Intercepting service Lambda
Serverless: Intercepting service Kinesis
Serverless: config.options_stage: local
Serverless: serverless.service.custom.stage: undefined
Serverless: serverless.service.provider.stage: local
Serverless: Using serverless-localstack-plugin
Serverless: Reconfiguring service S3 to use http://localhost:4572
Serverless: Reconfiguring service DynamoDB to use http://localhost:4570
Serverless: Reconfiguring service CloudFormation to use http://localhost:4581
Serverless: Reconfiguring service Elasticsearch to use http://localhost:4571
Serverless: Reconfiguring service ES to use http://localhost:4578
Serverless: Reconfiguring service SNS to use http://localhost:4575
Serverless: Reconfiguring service SQS to use http://localhost:4576
Serverless: Reconfiguring service Lambda to use http://localhost:4574
Serverless: Reconfiguring service Kinesis to use http://localhost:4568
Serverless: Invoke aws:deploy:deploy
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Validating template...
Serverless: Skipping template validation: Unsupported in Localstack
Serverless: Updating Stack...
 
  Serverless Error ---------------------------------------
 
 
  Stack Trace --------------------------------------------
 
ServerlessError: null
    at BbPromise.fromCallback.catch.err (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:258:33)
From previous event:
    at persistentRequest (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:247:13)
    at doCall (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:205:9)
    at BbPromise (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:216:14)
From previous event:
    at persistentRequest (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:203:38)
    at Object.request.requestQueue.add [as promiseGenerator] (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:237:49)
    at Queue._dequeue (/usr/local/lib/node_modules/serverless/node_modules/promise-queue/lib/index.js:153:30)
    at /usr/local/lib/node_modules/serverless/node_modules/promise-queue/lib/index.js:109:18
From previous event:
    at Queue.add (/usr/local/lib/node_modules/serverless/node_modules/promise-queue/lib/index.js:94:16)
    at AwsProvider.request (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:237:39)
    at LocalstackPlugin.interceptRequest (/usr/local/lib/node_modules/serverless-localstack/src/index.js:150:17)
    at AwsDeploy.update (/usr/local/lib/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:81:26)
From previous event:
    at AwsDeploy.BbPromise.bind.then (/usr/local/lib/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:101:12)
From previous event:
    at AwsDeploy.updateStack (/usr/local/lib/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:95:8)
From previous event:
    at AwsDeploy.BbPromise.bind.then (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:135:39)
From previous event:
    at Object.aws:deploy:deploy:updateStack [as hook] (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:131:10)
    at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:372:55)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:372:22)
    at PluginManager.spawn (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:390:17)
    at AwsDeploy.BbPromise.bind.then (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:101:48)
From previous event:
    at Object.deploy:deploy [as hook] (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:97:10)
    at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:372:55)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:372:22)
    at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:403:17)
    at variables.populateService.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:102:33)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:89:74)
    at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless:42:50)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           7.4.0
     Serverless Version:     1.26.1
```

**Comment by bsarazin** [comment]
I am seeing the same issue

I can query the s3 bucket and verify the files exist and also see the cloud formation stack exists, but the UPDATE fails:

```
aws s3 ls s3://aws-nodejs-local-ServerlessDeploymentBucket-9A-Z7563990495 --recursive --human-readable --summarize --endpoint-url=http://localhost:4572 
2018-03-10 15:55:07    6.3 KiB serverless/aws-nodejs/local/1520718901202-2018-03-10T21:55:01.202Z/aws-nodejs.zip
2018-03-10 15:55:07    2.0 KiB serverless/aws-nodejs/local/1520718901202-2018-03-10T21:55:01.202Z/compiled-cloudformation-template.json
2018-03-10 15:55:49    6.3 KiB serverless/aws-nodejs/local/1520718948375-2018-03-10T21:55:48.375Z/aws-nodejs.zip
2018-03-10 15:55:49    2.0 KiB serverless/aws-nodejs/local/1520718948375-2018-03-10T21:55:48.375Z/compiled-cloudformation-template.json
2018-03-10 16:01:39    6.3 KiB serverless/aws-nodejs/local/1520719297639-2018-03-10T22:01:37.639Z/aws-nodejs.zip
2018-03-10 16:01:39    2.0 KiB serverless/aws-nodejs/local/1520719297639-2018-03-10T22:01:37.639Z/compiled-cloudformation-template.json
```

```
aws cloudformation list-stacks --endpoint http://localhost:4581
{
    "StackSummaries": [
        {
            "StackId": "arn:aws:cloudformation:us-east-1:123456789:stack/aws-nodejs-local/32bb9ca3-df06-45ef-acb2-5bada4faf618", 
            "StackName": "aws-nodejs-local", 
            "CreationTime": "2011-05-23T15:47:44Z", 
            "StackStatus": "CREATE_COMPLETE", 
            "TemplateDescription": "The AWS CloudFormation template for this Serverless application"
        }
    ]
}
```

**Comment by juancho088** [comment]
I was having a lot issues with this plugin and Java 8 (actually I'm still having). Have in mind this:
https://github.com/localstack/localstack/issues/385

Localstack has a problem with the ZIP & Jar: Is not following the canonical way. So if you're using gradle you can always workaround that issue using something like this:

```
task buildZip(type: Zip, dependsOn: shadowJar) {
    from 'build/libs/'
    include '*-all.jar'
    archiveName "${group}-${version}-all.zip"
    destinationDir(file('build/libs/'))

}

task deploy(type: Exec, dependsOn: 'buildZip') {
    commandLine 'serverless', 'deploy'
}
```

Don't forget to change in your serverless.yml file the extension of the artifact to .zip. Be careful with this option, because in the real infrastructure is going to fail. However I'm still having this issue at the end:

```
  Serverless Error ---------------------------------------

  Attribute without value
Line: 13
Column: 70
Char: a

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.9.1
     Serverless Version:     1.25.0
```

And is not capable to create the API Gateway.

**Comment by gowtham7788** [comment]
I have the following error while i try to deploy in localstack

`Serverless Error ---------------------------------------

  ServerlessError: Attribute without value
Line: 13
Column: 70
Char: a

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           8.10.0
     Serverless Version:     1.26.1`

**Comment by st33v** [comment]
see also #24
