### ISSUE TITLE
getting invalid xml error when deploying to localstack

### ISSUE THREAD

**Issue by tonyzeng91** [temyers/serverless-localstack#36]
When deploying to localstack the process fails with 'Recoverable error occured(null)' and in the traceback I see that it is complaining about an invalid xml. Any idea on the fix? 

```Serverless: Reconfiguring service SQS to use http://localhost:4576
Serverless: Recoverable error occured (null), sleeping 5 seconds. Try 1 of 4
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
..
Serverless: Stack create finished...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service .zip file to S3 (18.1 MB)...
Serverless: Validating template...
Serverless: Skipping template validation: Unsupported in Localstack
Serverless: Updating Stack...
Serverless: Recoverable error occured (null), sleeping 5 seconds. Try 1 of 4
Serverless: Recoverable error occured (null), sleeping 5 seconds. Try 2 of 4
Serverless: Recoverable error occured (null), sleeping 5 seconds. Try 3 of 4
Serverless: Recoverable error occured (null), sleeping 5 seconds. Try 4 of 4```

Traceback: 

```Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 215, in forward
    updated_response = self.proxy.update_listener.return_response(**kwargs)
  File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_listener.py", line 216, in return_response
    template_deployer.deploy_template(template, req_data.get('StackName')[0])
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 509, in deploy_template
    stack_resources = describe_stack_resources(stack_name, resource_id)
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 227, in describe_stack_resources
    resources = client.describe_stack_resources(StackName=stack_name, LogicalResourceId=logical_resource_id)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/client.py", line 599, in _make_api_call
    operation_model, request_dict)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/endpoint.py", line 148, in make_request
    return self._send_request(request_dict, operation_model)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/endpoint.py", line 175, in _send_request
    request, operation_model, attempts)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/endpoint.py", line 256, in _get_response
    response_dict, operation_model.output_shape)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/parsers.py", line 240, in parse
    parsed = self._do_error_parse(response, shape)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/parsers.py", line 473, in _do_error_parse
    root = self._parse_xml_string_to_dom(xml_contents)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/parsers.py", line 425, in _parse_xml_string_to_dom
    "invalid XML received:\n%s" % (e, xml_string))
ResponseParserError: Unable to parse response (syntax error: line 1, column 54), invalid XML received:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
```

**Comment by garethmcc** [comment]
I am getting exactly the same. Have nothing additional to add to help with debugging except to point out its not just happening @tonyzeng91

**Comment by carstenwawer** [comment]
Getting the exact error. Trying to start Localstack via Docker on Mac...

**Comment by johnbarry343** [comment]
Has anyone found a workaround that can be pulled into the appropriate codebase?

**Comment by beau6183** [comment]
Also hoping for a patch or a workaround...

**Comment by garethmcc** [comment]
@temyers Any idea what may be causing the issue?

**Comment by temyers** [comment]
Hi,
Since this plugin is a simple wrapper to inject endpoints to point to localstack, the error above looks to be an underlying localstack issue.

I can't give much more info on debugging it at the moment, but creating a [MCVE](https://stackoverflow.com/help/mcve) and raising with localstack should be your first point of call.

Note that the localstack maintainers don't necessarily use, or are familiar with, Serverless Framework.  Therefore the MCVE should be in terms of the CloudFormation, and associated resources/calls.

Therefore:
* `serverless package` will generate the template and upload zip files that can form part of the MCVE.
* Serverless performs the following functions during deploy:
** Queries for the existence of the function stack
** Creates the serverless stack if necessary, which creates the S3 bucket
** Uploads zip files to the S3 bucket
** Updates the stack, to deploy your functions/API Gateway/additional resources.

From the errors above, the update is failing.  Either due to some race condition or unimplemented functionality within localstack.

**Comment by temyers** [comment]
Since this looks to be an underlying issue with localstack, closing this issue
