### ISSUE TITLE
'TypeError: Cannot read property 'endpoint' of undefined' when deploying

### ISSUE THREAD

**Issue by CRogers** [temyers/serverless-localstack#43]
After [adding serverless-localstack to my project like this](https://github.com/CRogers/serverless-extreme-startup/commit/1c809c6f7ab33fa500caf977be14863f940f736d), when I try and deploy locally I get an error:

```
$ SLS_DEBUG=1 yarn run serverless deploy -v --stage local
yarn run v1.9.4
warning package.json: No license field
$ ./serverless-extreme-startup/backend/node_modules/.bin/serverless deploy -v --stage local
Serverless: Load command config
# snip many commands
Serverless: Load command deploy
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Invoke aws:common:validate
Serverless: config.options_stage: local
Serverless: serverless.service.custom.stage: undefined
Serverless: serverless.service.provider.stage: prod
Serverless: Using serverless-localstack
Serverless: Reconfiguring service apigateway to use http://localhost:4567
Serverless: Reconfiguring service cloudformation to use http://localhost:4581
Serverless: Reconfiguring service cloudwatch to use http://localhost:4582
Serverless: Reconfiguring service lambda to use http://localhost:4574
Serverless: Reconfiguring service dynamodb to use http://localhost:4567
Serverless: Reconfiguring service s3 to use http://localhost:4572
Serverless: Reconfiguring service ses to use http://localhost:4579
Serverless: Reconfiguring service sns to use http://localhost:4575
Serverless: Reconfiguring service sqs to use http://localhost:4576
Serverless: Reconfiguring service s3 to use http://localhost:4572
Serverless: Reconfiguring service dynamodb to use http://localhost:4570
Serverless: Reconfiguring service cloudformation to use http://localhost:4581
Serverless: Reconfiguring service elasticsearch to use http://localhost:4571
Serverless: Reconfiguring service es to use http://localhost:4578
Serverless: Reconfiguring service sns to use http://localhost:4575
Serverless: Reconfiguring service sqs to use http://localhost:4576
Serverless: Reconfiguring service lambda to use http://localhost:4574
Serverless: Invoke aws:deploy:deploy

  Serverless Error ---------------------------------------

  TypeError: Cannot read property 'endpoint' of undefined

  Stack Trace --------------------------------------------

ServerlessError: TypeError: Cannot read property 'endpoint' of undefined
    at AwsDeploy.BbPromise.bind.then.catch (./serverless-extreme-startup/backend/node_modules/serverless/lib/plugins/aws/deploy/lib/createStack.js:90:15)
From previous event:
    at AwsDeploy.createStack (./serverless-extreme-startup/backend/node_modules/serverless/lib/plugins/aws/deploy/lib/createStack.js:81:13)
From previous event:
    at Object.aws:deploy:deploy:createStack [as hook] (./serverless-extreme-startup/backend/node_modules/serverless/lib/plugins/aws/deploy/index.js:102:10)
    at BbPromise.reduce (./serverless-extreme-startup/backend/node_modules/serverless/lib/classes/PluginManager.js:390:55)
From previous event:
    at PluginManager.invoke (./serverless-extreme-startup/backend/node_modules/serverless/lib/classes/PluginManager.js:390:22)
    at PluginManager.spawn (./serverless-extreme-startup/backend/node_modules/serverless/lib/classes/PluginManager.js:408:17)
    at AwsDeploy.BbPromise.bind.then (./serverless-extreme-startup/backend/node_modules/serverless/lib/plugins/aws/deploy/index.js:95:48)
From previous event:
    at Object.deploy:deploy [as hook] (./serverless-extreme-startup/backend/node_modules/serverless/lib/plugins/aws/deploy/index.js:91:10)
    at BbPromise.reduce (./serverless-extreme-startup/backend/node_modules/serverless/lib/classes/PluginManager.js:390:55)
From previous event:
    at PluginManager.invoke (./serverless-extreme-startup/backend/node_modules/serverless/lib/classes/PluginManager.js:390:22)
    at PluginManager.run (./serverless-extreme-startup/backend/node_modules/serverless/lib/classes/PluginManager.js:421:17)
    at variables.populateService.then.then (./serverless-extreme-startup/backend/node_modules/serverless/lib/Serverless.js:157:33)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
    at process.topLevelDomainCallback (domain.js:121:23)
From previous event:
    at Serverless.run (./serverless-extreme-startup/backend/node_modules/serverless/lib/Serverless.js:144:8)
    at serverless.init.then (./serverless-extreme-startup/backend/node_modules/serverless/bin/serverless:43:50)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           10.10.0
     Serverless Version:     1.31.0

error Command failed with exit code 1.
```

Not sure what's going on, I just added the config out of the readme!

**Comment by justinm** [comment]
Likely related to https://github.com/temyers/serverless-localstack/pull/41

**Comment by CRogers** [comment]
Looks like 0.3.1 fixed it, thanks!
