### ISSUE TITLE
Recoverable error occurred (null)

### ISSUE THREAD

**Issue by jdwil** [temyers/serverless-localstack#45]
I'm running the latest serverless, serverless-localstack and localstack. I'm running localstack via

`localstack run --docker`

I've seen this error in various issues here and on localstack, but mostly they seem to be resolved with later versions of the software, which doesn't seem to be my case. 

Here are the pertinent parts of my serverless.yml:

```
service: app-api

custom:
  localstack:
    stages:
      - local
    host: http://localhost
    endpointFile: ../localstack.json

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-west-2

  iamRoleStatements:
  - Effect: "Allow"
    Action:
      - "sns:*"
    Resource: "*"
  - Effect: "Allow"
    Action:
      - "s3:*"
    Resource: "*"

functions:
  my_func:
    handler: my_func.handler
    events:
      - http:
          path: my_func
          method: put
          cors: true
          authorizer:
            arn: ...

...

plugins:
  - serverless-localstack
```

When I run sls deploy --stage local I get:

```
$ sls deploy --stage local --debug
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command requirements
Serverless: Load command requirements:clean
Serverless: Load command requirements:install
Serverless: Load command deploy
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Installing requirements of requirements.txt in .serverless...
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Injecting required Python packages to package...
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Invoke aws:common:validate
Serverless: Loading endpointJson from ../localstack.json
Serverless: Intercepting service APIGateway
Serverless: Intercepting service CloudFormation
Serverless: Intercepting service CloudWatch
Serverless: Intercepting service DynamoDB
Serverless: Intercepting service DynamoDBStreams
Serverless: Intercepting service ES
Serverless: Intercepting service Firehose
Serverless: Intercepting service Kinesis
Serverless: Intercepting service Lambda
Serverless: Intercepting service Redshift
Serverless: Intercepting service Route53
Serverless: Intercepting service S3
Serverless: Intercepting service SES
Serverless: Intercepting service SNS
Serverless: Intercepting service SQS
Serverless: config.options_stage: local
Serverless: serverless.service.custom.stage: undefined
Serverless: serverless.service.provider.stage: dev
Serverless: Using serverless-localstack
Serverless: Reconfiguring service apigateway to use http://localhost:4567
Serverless: Reconfiguring service cloudformation to use http://localhost:4581
Serverless: Reconfiguring service cloudwatch to use http://localhost:4582
Serverless: Reconfiguring service lambda to use http://localhost:4574
Serverless: Reconfiguring service dynamodb to use http://localhost:4567
Serverless: Reconfiguring service s3 to use http://localhost:4572
Serverless: Reconfiguring service ses to use http://localhost:4579
Serverless: Reconfiguring service sns to use http://localhost:4575
Serverless: Reconfiguring service sqs to use http://localhost:4576
Serverless: Reconfiguring service APIGateway to use http://localhost:4567
Serverless: Reconfiguring service CloudFormation to use http://localhost:4581
Serverless: Reconfiguring service CloudWatch to use http://localhost:4582
Serverless: Reconfiguring service DynamoDB to use http://localhost:4569
Serverless: Reconfiguring service DynamoDBStreams to use http://localhost:4570
Serverless: Reconfiguring service ES to use http://localhost:4571
Serverless: Reconfiguring service Firehose to use http://localhost:4573
Serverless: Reconfiguring service Kinesis to use http://localhost:4568
Serverless: Reconfiguring service Lambda to use http://localhost:4574
Serverless: Reconfiguring service Redshift to use http://localhost:4577
Serverless: Reconfiguring service Route53 to use http://localhost:4580
Serverless: Reconfiguring service S3 to use http://localhost:4572
Serverless: Reconfiguring service SES to use http://localhost:4579
Serverless: Reconfiguring service SNS to use http://localhost:4575
Serverless: Reconfiguring service SQS to use http://localhost:4576
Serverless: Invoke aws:deploy:deploy
Serverless: Creating Stack...
Serverless: Recoverable error occurred (null), sleeping for 5 seconds. Try 1 of 4
Serverless: Recoverable error occurred (null), sleeping for 5 seconds. Try 2 of 4
Serverless: Recoverable error occurred (null), sleeping for 5 seconds. Try 3 of 4
Serverless: Recoverable error occurred (null), sleeping for 5 seconds. Try 4 of 4
 
  Serverless Error ---------------------------------------
 
 
  Stack Trace --------------------------------------------
 
ServerlessError: null
    at BbPromise.fromCallback.catch.err (/usr/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:270:11)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at persistentRequest (/usr/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:253:13)
    at Timeout.doCall [as _onTimeout] (/usr/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:205:9)
    at ontimeout (timers.js:502:15)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           8.12.0
     Serverless Version:     1.32.0

```

And in localstack, I get errors like this:

```
2018-09-21T16:03:48:ERROR:localstack.services.generic_proxy: Error forwarding request: An error occurred (ValidationError) when calling the DescribeStackResources operation: Stack with name app-api-local does not exist Traceback (most recent call last):
File "/opt/code/localstack/localstack/services/generic_proxy.py", line 218, in forward
updated_response = self.proxy.update_listener.return_response(**kwargs)
File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_listener.py", line 216, in return_response
template_deployer.deploy_template(template, req_data.get('StackName')[0])
File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 509, in deploy_template
stack_resources = describe_stack_resources(stack_name, resource_id)
File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 227, in describe_stack_resources
resources = client.describe_stack_resources(StackName=stack_name, LogicalResourceId=logical_resource_id)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/client.py", line 320, in _api_call
return self._make_api_call(operation_name, kwargs)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/client.py", line 623, in _make_api_call
raise error_class(parsed_response, operation_name)
ClientError: An error occurred (ValidationError) when calling the DescribeStackResources operation: Stack with name app-api-local does not exist
```

**Comment by justinm** [comment]
I think this may be relate to #38

**Comment by daviskoh** [comment]
I think it may be a diff issue.

I forked and cloned the localstack repo then patched in the `"AWS::Partition": "aws"` change into `moto/cloudformation/parsing.py`, but am still getting the error

**Comment by danny-waite** [comment]
to confirm, I'm getting the same issue here

**Comment by gregevari** [comment]
Looks like this one is on the localstack side: https://github.com/localstack/localstack/issues/438

**Comment by temyers** [comment]
This project is no longer being actively maintained, so shall be archiving the repository
